import Header from './components/Header'
import Navbar from './components/Navbar'
import { Inter } from 'next/font/google'
import './globals.css'
import Vert_Navbar from './components/Vert_Navbar'
import Navbar_V from './components/Navbar_V'

const inter = Inter({ subsets: ['latin'] })


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className='flex justify-start bg-[#1E1A1E]' >
          <div className=''><Navbar_V/></div>
          <div className='w-full'>{children}</div>
        </main>
      </body>
    </html>
  )
}
